Upgraded to version 0.1.4

diff --git a/pacrep b/pacrep
--- a/pacrep
+++ b/pacrep
@@ -14,7 +14,7 @@
 ### PROGRAM DATA ###
 
 ME="PacRep"
-VERSION="0.1.3"
+VERSION="0.1.4"
 AUTHOR="L. Abramovich"
 DATE="Dec, 2020"
 LICENSE="GPL2+"
@@ -22,9 +22,9 @@ WEBSITE="https://github.com/leo-arch/pacrep"
 
 [[ $SUDO_USER ]] && user=$SUDO_USER || user=$USER
 if [[ $user == "root" ]]; then
-	CONFIG_DIR="/root/.config/pacrep"
+	CONFIG_DIR="/root/.config/${ME,,}"
 else
-	CONFIG_DIR="/home/$user/.config/pacrep"
+	CONFIG_DIR="/home/$user/.config/${ME,,}"
 fi
 
 CONFIG_FILE="$CONFIG_DIR/${ME,,}.conf"
@@ -46,9 +46,8 @@ function echoerr ()
 
 function help ()
 {
-	echo "PacRep: Choose pacman repositories on a per package basis"
-	echo "Usage: ${ME,,} [-a,--all] [-s,--single PKG(s)] [-h,--help] \
-[-v,--version]
+	echo "${ME}: Choose pacman repositories on a per package basis
+Usage: ${ME,,} [OPTIONS] [PKG(s)]
 
 -a, --all		Update and upgrade the system
 -s, --single PKG(s)	Install PKG(s)
@@ -91,8 +90,14 @@ case $1 in
 	-v|--version) version; exit $EXIT_SUCCESS ;;
 
 	-l|--list)
-		/usr/bin/grep -v "^$\|^#" "$CONFIG_FILE" | /usr/bin/column
-		exit $EXIT_SUCCESS
+		# Return error if any of the pipe commands fails 
+		set -o pipefail
+		if /usr/bin/grep -v "^$\|^#" "$CONFIG_FILE" \
+		| /usr/bin/column; then
+			exit $EXIT_SUCCESS
+		else
+			exit $EXIT_FAILURE
+		fi
 	;;
 
 	-d|--dry-run)
@@ -121,7 +126,10 @@ case $1 in
 	# Single package(s) mode
 	-s|--single) shift; ups=( "$@" ) ;;
 
-	*) echoerr "${ME,,}: '$1': Invalid parameter"; exit $EXIT_FAILURE ;;
+	*)
+		echoerr "${ME,,}: '$1': Invalid parameter"
+		exit $EXIT_FAILURE
+	;;
 esac
 
 if [[ ${#ups[*]} -eq 0 ]]; then
@@ -143,8 +151,8 @@ remaining_install=( ${ups[*]} )
 
 for (( i=0;i<${#ups[*]};i++ )); do
 
-	# If repo was already specified in command line (repo/pkg), skip the rules
-	#+ test
+	# If repo was already specified in command line (repo/pkg), skip 
+	#+ the rules test
 	if [[ ${ups[$i]} == *"/"* ]]; then
 		continue
 	fi
@@ -152,7 +160,8 @@ for (( i=0;i<${#ups[*]};i++ )); do
 	for (( j=0;j<${#rules[*]};j++ )); do
 		if [[ ${ups[$i]} == ${rules[$j]##*/} ]]; then
 			# If a rule for the pkg is found, add the pkg to the ruled
-			#+ pkgs list and remove it from the non-ruled list
+			#+ pkgs list, remove it from the non-ruled list, and exit
+			#+ the for loop: there is nothing else to check
 			rules_install[${#rules_install[*]}]="${rules[$j]%%/*}/${ups[$i]}"
 			unset 'remaining_install[$i]'
 			break
@@ -163,14 +172,20 @@ done
 ### DRY-RUN: Just print and exit ###
 
 if [[ $dry_run -eq 1 ]]; then
-	echo "Ruled packages: ${rules_install[*]}
-Non-ruled packages: ${remaining_install[*]}"
+	if [[ ${#rules_install[*]} -gt 0 ]]; then
+		echo "Ruled packages: ${rules_install[*]}"
+	fi
+
+	if [[ ${#remaining_install[*]} -gt 0 ]]; then
+		echo "Non-ruled packages: ${remaining_install[*]}"
+	fi
+
 	exit $EXIT_SUCCESS
 fi
 
 ### INSTALL RULED PACKAGES, IF ANY ###
 
-if [[ ${#rules_install[@]} -eq 0 ]]; then
+if [[ ${#rules_install[*]} -eq 0 ]]; then
 	echo -e "${green} ->$nc$bold No ruled packages found$nc\n"
 else
 	echo -e "${green} ->$nc$bold Ruled packages found:$nc"
@@ -191,7 +206,9 @@ fi
 ### INSTALL REMAINING PACKAGES, IF ANY ###
 
 if [[ ${#remaining_install[*]} -gt 0 ]]; then
-	/usr/bin/$PACMAN -S ${remaining_install[*]}
+	if ! /usr/bin/$PACMAN -S ${remaining_install[*]}; then
+		exit $EXIT_FAILURE
+	fi
 fi
 
 exit $EXIT_SUCCESS
